## Step 1: Data Exploration

* Investigate and understand the data and its values
* Visualize the data (scatter plots, histograms, heatmaps).
* Investigate the correlation of the values with the exam_grade.

In [8]:
## Imports
import pandas as pd

In [9]:
df = pd.read_csv('data/StudentPerformanceFactors.csv')
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [10]:
# overview over the data structure
data_info = df.info()

data_info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB

In [11]:
data_head = df.head()

data_info, data_head

(None,
    Hours_Studied  Attendance Parental_Involvement Access_to_Resources  \
 0             23          84                  Low                High
 1             19          64                  Low              Medium
 2             24          98               Medium              Medium
 3             29          89                  Low              Medium
 4             19          92               Medium              Medium

   Extracurricular_Activities  Sleep_Hours  Previous_Scores Motivation_Level  \
 0                         No            7               73              Low
 1                         No            8               59              Low
 2                        Yes            7               91           Medium
 3                        Yes            8               98           Medium
 4                        Yes            6               65           Medium

   Internet_Access  Tutoring_Sessions Family_Income Teacher_Quality  \
 0             Yes                  0           Low          Medium
 1             Yes                  2        Medium          Medium
 2             Yes                  2        Medium          Medium
 3             Yes                  1        Medium          Medium
 4             Yes                  3        Medium            High

   School_Type Peer_Influence  Physical_Activity Learning_Disabilities  \
 0      Public       Positive                  3                    No
 1      Public       Negative                  4                    No
 2      Public        Neutral                  4                    No
 3      Public       Negative                  4                    No
 4      Public        Neutral                  4                    No

   Parental_Education_Level Distance_from_Home  Gender  Exam_Score
 0              High School               Near    Male          67
 1                  College           Moderate  Female          61
 2             Postgraduate               Near    Male          74
 3              High School           Moderate    Male          71
 4                  College               Near  Female          70  )

In [12]:
# Check for missing values
df.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64